local config = {}

-- function config.todo()
-- 	require("todo-comments").setup({
-- 		keywords = {
-- 			FIX = {
-- 				icon = " ",
-- 				color = "error",
-- 				alt = { "FIXME", "BUG", "FIXIT", "ISSUE" },
-- 			},
-- 			TODO = { icon = " ", color = "info" },
-- 			HACK = { icon = " ", color = "warning" },
-- 			WARN = { icon = " ", color = "warning", alt = { "WARNING", "XXX" } },
-- 			PERF = { icon = " ", alt = { "OPTIM", "PERFORMANCE", "OPTIMIZE" } },
-- 			NOTE = { icon = " ", color = "hint", alt = { "INFO" } },
-- 		},
-- 		highlight = {
-- 			before = "",
-- 			keyword = "wide",
-- 			after = "fg",
-- 		},
-- 		search = {
-- 			command = "rg",
-- 			args = {
-- 				"--color=never",
-- 				"--no-heading",
-- 				"--with-filename",
-- 				"--line-number",
-- 				"--column",
-- 			},
-- 			pattern = [[\b(KEYWORDS):]],
-- 			ignore_case = true,
-- 		},
-- 		colors = {
-- 			error = { "LspDiagnosticsDefaultError", "ErrorMsg", "#DC2626" },
-- 			warning = { "LspDiagnosticsDefaultWarning", "WarningMsg", "#FBBF24" },
-- 			info = { "LspDiagnosticsDefaultInformation", "#2563EB" },
-- 			hint = { "LspDiagnosticsDefaultHint", "#10B981" },
-- 			default = { "Identifier", "#7C3AED" },
-- 		},
-- 		-- filter with per filetypes
-- 		filetypes = {
-- 			markdown = {
-- 				HACK = { icon = " ", color = "warning", alt = { "FIXME", "BUG", "FIXIT", "ISSUE" } },
-- 			},
-- 		},
-- 		-- filter keyword patterns
-- 		patterns = {
-- 			".*",
-- 		},
-- 	})
-- end

return config
