-- https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/gopls.lua
return {
	flags = { debounce_text_changes = 500 },
	cmd = { "gopls", "-remote=auto" },
	settings = {
		gopls = {
			usePlaceholders = true,
			codelenses = {
				generate = true, -- show the `go generate` lens.
				gc_details = true, -- Show a code lens toggling the display of gc's choices.
				test = true,
				tidy = true,
				regenerate_cgo = true,
				run_vulncheck_exp = true,
				upgrade_dependency = true,
			},
			directoryFilters = {
				"-**/node_modules",
				"-/tmp",
			},
			verboseOutput = false, -- useful for debugging when true.
			semanticTokens = true,
			completeUnimported = true,
			completionDocumentation = true,
			staticcheck = true,
			gofumpt = true,
			linksInHover = true,
			buildFlags = { "-tags=integration,e2e" },
			analyses = {
				asmdecl = true, -- report mismatches between assembly files and Go declarations      (JeffreyGuan 1 week ago) init
				assign = true, -- check for useless assignments
				atomic = true, -- check for common mistakes using the sync/atomic package
				atomicalign = true, -- check for non-64-bits-aligned arguments to sync/atomic functions
				bools = true,
				buildtag = true,
				cgocall = true,
				composites = true,
				copylocks = true,
				deepequalerrors = true,
				embed = true,
				errorsas = true,
				fieldalignment = true,
				httpresponse = true,
				ifaceassert = true,
				infertypeargs = true,
				loopclosure = true,
				lostcancel = true,
				nilfunc = true,
				nilness = true,
				printf = true,
				shadow = true,
				shift = true,
				simplifycompositelit = true,
				simplifyrange = true,
				simplifyslice = true,
				sortslice = true,
				stdmethods = true,
				stringintconv = true,
				structtag = true,
				testinggoroutine = true,
				tests = true,
				timeformat = true,
				unmarshal = true,
				unreachable = true,
				unsafeptr = true,
				unusedparams = true,
				unusedresult = true,
				unusedwrite = true,
				useany = true,
				fillreturns = true,
				nonewvars = true,
				noresultvalues = true,
				undeclaredname = true,
				unusedvariable = true,
				fillstruct = true,
				stubmethods = true,
			},
		},
	},
}
